# Generated by Django 3.2.9 on 2021-11-24 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('place', models.CharField(max_length=30, verbose_name='Place')),
                ('work_time', models.CharField(max_length=10, verbose_name='Busyness')),
                ('salary', models.CharField(max_length=20, verbose_name='Salary')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'db_table': 'work',
            },
        ),
    ]
