# Generated by Django 3.2.9 on 2021-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_class',
            field=models.CharField(default=1, max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
