# Generated by Django 3.2.9 on 2021-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_work_work_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_class',
            field=models.CharField(max_length=50, verbose_name='Class'),
        ),
    ]
