# Generated by Django 3.2.9 on 2021-11-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link_em',
            new_name='Link',
        ),
    ]
